name: 编译

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, windows-2025, ubuntu-latest]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          # WyriHaximus/github-action-get-previous-tag@master need it
          fetch-depth: 0
          submodules: true
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          # this is not supported, use dev branch instead
          # xmake-version: local#
          xmake-version: branch@dev

      # Cache xmake dependencies
      - name: 配置依赖缓存
        uses: actions/cache@v3
        with:
          path: xmake-cache
          key: ${{ matrix.os }}-${{ matrix.arch }}-v6

      - name: 设置xmake相关目录
        run: |
          xmake g --pkg_cachedir=$(pwd)/xmake-cache/cache
          xmake g --pkg_installdir=$(pwd)/xmake-cache/packages
          xmake repo -u
      
      - name: 配置opengl环境
        if: runner.os != 'Windows'
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: libgl1-mesa-dev libglu1-mesa-dev
          version: 2

      - name: 编译debug版本
        run: |
          xmake f -cy --with_test=y -m debug
          xmake

      - name: 编译release版本
        run: |
          xmake f -cy --with_test=y -m release
          xmake

      - name: 打包项目
        run: |
          xmake f -cy --with_test=y -m release
          xmake pack -f zip -o artifacts/ --basename=SpaceAST
          
      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: SpaceAST-${{ matrix.os }}-${{ matrix.arch }}.zip
          path: artifacts/SpaceAST.zip
           
      - name: Publish
        if: github.event.action == 'published'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/SpaceAST.zip
          asset_name: SpaceAST-${{ matrix.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip
